### ISSUE TITLE
Question about cron running and this module

### ISSUE THREAD

**Issue by dficker** [backdrop-contrib/google_tag#3]
In Backdrop, how often does cron run normally? How does it get increased/decreased in regularity?

Looking at this module, it seems to me like rebuilding the JS files every time cron runs may be a bit too often? (Depending on how cron runs overall.)

https://github.com/backdrop-contrib/google_tag/blob/1.x-1.x/google_tag.module#L87-L89

At least, maybe, depending on how else cron is being used on the site?

**Comment by laryn** [comment]
That certainly looks suspect!

**Comment by laryn** [comment]
It looks like it used to be that way in Drupal 7 as well, but has been changed. Which probably means there are a bunch of updates from the D7 module that should get pulled in here.

https://git.drupalcode.org/project/google_tag/-/commit/03b443583069e9d163ba292e6b982052d7955794
