### ISSUE TITLE
Co-maintainer request

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/google_tag#4]
@jenlampton and @kthull I may have some time to bring this up to par with the Drupal 7 version (e.g. pull a few commits into `1.x-1.x` and then port the now-recommended branch into `1.x-2.x`). I am requesting co-maintainer access since you indicate in the README that you are seeking additional maintainers.

**Comment by jenlampton** [comment]
I've merged the PR and added you as an admin to the repo.
